openapi: 3.0.3
info:
  title: API Biblioteca
  version: 1.0.0
paths:
  /api/cursos:
    post:
      summary: Registrar un nuevo libro
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/Curso' } } } }
      responses: { '201': { description: Curso registrado } }
    get:
      summary: Consultar todos los cursos
      responses: { '200': { description: Lista de cursos } }
  /api/cursos/codigo/{codigo}:
    get:
      summary: Consultar libro por título
      parameters: [{ name: codigo, in: path, required: true, schema: { type: string } }]
      responses: { '200': { description: Curso encontrado }, '404': { description: No encontrado } }
  /api/cursos/{id}:
    put:
      summary: Actualizar libro
      parameters: [{ name: id, in: path, required: true, schema: { type: integer } }]
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/Curso' } } } }
      responses: { '200': { description: Actualizado }, '404': { description: No encontrado } }
    delete:
      summary: Eliminar libro
      parameters: [{ name: id, in: path, required: true, schema: { type: integer } }]
      responses: { '204': { description: Eliminado }, '404': { description: No encontrado } }
components:
  schemas:
    Curso:
      type: object
      properties: { id: { type: integer }, codigo: { type: string }, nombre: { type: string }, creditos: { type: string }, anioPublicacion: { type: integer }, estado: { type: string } }