openapi: 3.0.3
info:
  title: API Biblioteca
  version: 1.0.0
paths:
  /api/reservas:
    post:
      summary: Registrar un nuevo libro
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/Reserva' } } } }
      responses: { '201': { description: Reserva registrado } }
    get:
      summary: Consultar todos los reservas
      responses: { '200': { description: Lista de reservas } }
  /api/reservas/id/{id}:
    get:
      summary: Consultar libro por título
      parameters: [{ name: id, in: path, required: true, schema: { type: string } }]
      responses: { '200': { description: Reserva encontrado }, '404': { description: No encontrado } }
  /api/reservas/{id}:
    put:
      summary: Actualizar libro
      parameters: [{ name: id, in: path, required: true, schema: { type: integer } }]
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/Reserva' } } } }
      responses: { '200': { description: Actualizado }, '404': { description: No encontrado } }
    delete:
      summary: Eliminar libro
      parameters: [{ name: id, in: path, required: true, schema: { type: integer } }]
      responses: { '204': { description: Eliminado }, '404': { description: No encontrado } }
components:
  schemas:
    Reserva:
      type: object
      properties: { id: { type: integer }, id: { type: string }, nombreCliente: { type: string }, habitacion: { type: string }, anioPublicacion: { type: integer }, estado: { type: string } }